apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: externalsecretcomposition
  labels:
    guide: "true"
spec:
  compositeTypeRef:
    apiVersion: mysecrets.example.org/v1alpha1
    kind: CompositeExternalSecret
  resources:
    - name: externalSecret
      base:
        apiVersion: external-secrets.io/v1beta1
        kind: ExternalSecret
        spec:
        # SecretStoreRef defines which SecretStore to use when fetching the secret data
        secretStoreRef:
          name: secret-store-name
          kind: SecretStore  
