apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: secretstorecomposition.example.com
spec:
  compositeTypeRef:
    apiVersion: example.com/v1
    kind: SecretStoreResource
  resources:
    - name: secretstore
      base:
        apiVersion: external-secrets.io/v1alpha1
        kind: SecretStore
        spec:
          provider:
            vault:
              server: ""
              path: secret/data
              version: v2
              auth:
                tokenSecretRef:
                  name: ""
                  key: ""
      patches:
        # Patch the vault server URL from the claim's spec.vaultServer
        - fromFieldPath: "spec.vaultServer"
          toFieldPath: "spec.provider.vault.server"
        
        # Patch the Vault token secret name from the claim's spec.vaultTokenSecretName
        - fromFieldPath: "spec.vaultTokenSecretName"
          toFieldPath: "spec.provider.vault.auth.tokenSecretRef.name"
        
        # Patch the Vault token secret key from the claim's spec.vaultTokenSecretKey
        - fromFieldPath: "spec.vaultTokenSecretKey"
          toFieldPath: "spec.provider.vault.auth.tokenSecretRef.key"
        
        # Patch the namespace for the SecretStore resource
        - fromFieldPath: "spec.namespace"
          toFieldPath: "metadata.namespace"
