apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeexternalsecrets.mysecrets.example.org
spec:
  group: mysecrets.example.org
  names:
    kind: CompositeExternalSecret
    plural: compositeexternalsecrets
  claimNames:
    kind: ExternalSecretClaim
    plural: externalsecretclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                providerConfigRef:
                  type: string
