
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
  namespace: default  # Change this to your desired namespace
spec:
  refreshInterval: "1h"  # How often to refresh the secret
  secretStoreRef:
    name: local-vault  # The name of your SecretStore
    kind: SecretStore   # Specify the type of the secret store
  target:
    name: my-k8s-secret  # Name of the Kubernetes Secret to create
    creationPolicy: Owner  # How to manage the lifecycle of the Secret
  data:
    - secretKey: foo  # The key in the Kubernetes Secret
      remoteRef:
        key: test
        property: foo
