apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-provider-clusterrole
rules:
  # Permissions for core API resources
  - apiGroups: [""]
    resources: ["namespaces", "serviceaccounts", "pods", "services", "configmaps", "secrets"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]

  # Permissions for apps resources (deployments, etc.)
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]

  # Permissions for RBAC resources
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings", "roles"]
    verbs: ["create", "get", "list", "watch"]

  # Permissions for CustomResourceDefinitions (CRDs)
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]

  # Permissions for compositeexternalsecrets in mysecrets.example.org API group
  - apiGroups: ["mysecrets.example.org"]
    resources: ["compositeexternalsecrets"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
