apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: local-vault
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  provider:
    vault:
      server: "http://vault.default.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
