apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: secretstorecomposition.example.com
spec:
  compositeTypeRef:
    apiVersion: example.com/v1
    kind: SecretStoreResource
  resources:
    - name: secretstore
      base:
        apiVersion: external-secrets.io/v1alpha1
        kind: SecretStore
        metadata:
          namespace: external-secrets
        spec:
          provider:
            vault:
              server: "http://vault.default.svc:8200"
              path: secret/data
              version: v2
              auth:
                tokenSecretRef:
                  name:  "vault-token"
                  namespace: default
                  key: "token"
      patches:
        - fromFieldPath: "spec.namespace"
          toFieldPath: "metadata.namespace"
