apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: secretstores.example.com
spec:
  group: example.com
  names:
    kind: SecretStoreResource
    plural: secretstores
  claimNames:
    kind: SecretStoreClaim
    plural: secretstoreclaims
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            namespace:
              type: string
