apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: iptapps.app.techcamp.ch  # Corrected name here
spec:
  group: app.techcamp.ch
  names:
    kind: IptApp
    plural: iptapps
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              location:
                type: string
                oneOf:
                  - pattern: '^EU$'
                  - pattern: '^US$'
            required:
              - location
    served: true
    referenceable: true
  claimNames:
    kind: IptAppClaims
    plural: iptappclaims

